### ISSUE TITLE
JSON.is

### ISSUE THREAD

**Issue by jdorfman** [jdorfman/awesome-help-wanted#14]
add http://json.is/ to https://github.com/jdorfman/awesome-json-datasets in other

**Comment by KhaledSamir** [comment]
Hi @jdorfman, Can you please elaborate the issue more?. I want to help out.

Thanks,
Khaled

**Comment by jdorfman** [comment]
hey @KhaledSamir totally forgot about this issue (and this repo). I'm going to close it since I recently had to [clean up the list](https://github.com/jdorfman/awesome-json-datasets/issues/175).

json.is is a great (and awesome) tool, it just doesn't fit the scope of the json-datasets list.

**Comment by KhaledSamir** [comment]
@jdorfman Thanks, Man. I'll try to help with other bugs as I'm a beginner to the OSS community 👍

**Comment by jdorfman** [comment]
@KhaledSamir awesome! Ping me if you ever need any help in that regard.  Also check out:

* http://up-for-grabs.net/
* http://www.firsttimersonly.com/
* https://helpwanted.apache.org/

**Comment by KhaledSamir** [comment]
@jdorfman Awesome! , Thank you very much. I'll check the links. Have a great holiday season! :)
